---
-  hosts: 172.31.16.182
   become: yes
   tasks: 
   - name: run linux command
     command: hostname -f
     register: myresult

   - name: display first task result
     debug: 
       msg: "{{myresult}}"