---
- hosts: 172.31.16.182
  become: yes
  tasks: 
  - name: install git
    apt:
      name: git
      state: present

  - name: install tree
    apt: 
      name: tree
      statee: present
    ignore_errors: true 
    

  - name: install wget
    apt: 
      name: wget
      state: present 