---
- hosts: 172.31.16.182
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: install webserver
    apt:
       name: apache2
       state: present

  - name: copy file into ansible node side
    copy: 
       src: staticfile.txt
       dest: /home/ubuntu/mystaticfile.txt

  - name: copy index.j2 file into ansible node side