---
- hosts: 172.31.16.182
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: install webserver
    apt:
       name: apache2
       state: present
    

  - name: copy file into ansible node side
    copy: 
       src: staticfile.txt
       dest: /home/ubuntu/mystaticfile.txt
    notify: restartwebserver   

  - #name: copy index.j2 file into ansible node side
    template:
        src: myindex.j2
        dest: /var/www/html/index.html
    #notify: restartwebserver

  - name: download internet files
    get_url:
      url: https://get.jenkins.io/war-stable/2.375.1/jenkins.war
      dest: /home/ubuntu/jenkins.war
      force_basic_auth: yes
  
  handlers:
  - name: restartwebserver
    service:
       name: apache2
       state: restarted