---
-  hosts: myWebServers
   become: yes
   tasks:
   - name: install webserver on ansible nodes
     apt:
        name: nginx
        state: latest
     when: ansible_os_family =="Debian"

   - name: start nginx webserver
     service: 
         name: nginx
         state: started
         enabled: yes
     when: ansible_os_family =="Debian"

   - name: install webserver on ansible nodes
     yum:
        name: httpd
        state: present
     when: ansible_os_family =="RedHat"

   - name: start webserver on ansible nodes
     service: 
         name: httpd
         state: started
     when: ansible_os_family =="RedHat"
