---
-  hosts: myWebServers
   become: yes
   tasks:
   - name: uninstall webserver on ansible nodes
     apt:
        name: nginx
        state: absent
     when: ansible_os_family =="Debian"

   - name: stop nginx webserver
     service: 
         name: nginx
         state: stopped
     when: ansible_os_family =="Debian"

   - name: install webserver on ansible nodes
     yum:
        name: httpd
        state: present
     when: ansible_os_family =="RedHat"

   - name: start webserver on ansible nodes
     service: 
         name: httpd
         state: started
     when: ansible_os_family =="RedHat"
