---
-  hosts: all
   become: yes
   tasks:
   - name: install webserver on ansible nodes
     apt:
        name: apache2
        state: present

   - name: start apache2 webserver
     service: 
         name: apache2
         state: restarted
