---
-  hosts: myWebServers
   become: yes
   tasks:
   - name: install webserver on ansible nodes
     apt:
        name: "{{webpackonubuntu}}"
        state: absent
     when: ansible_os_family =="Debian"

   - name: stop apache2 webserver
     service: 
         name: "{{webpackonubuntu}}"
         state: started
     when: ansible_os_family =="Debian"

   - name: install webserver on ansible nodes
     yum:
        name: "{{webpackonredhat}}"
        state: present
     when: ansible_os_family =="RedHat"

   - name: start webserver on ansible nodes
     service: 
         name: "{{webpackonredhat}}"
         state: started
     when: ansible_os_family =="RedHat"
